services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50021:50021"
    restart: always
    environment:
      - SERVER_PORT=50021
    networks:
      - autodl-network

networks:
  autodl-network:
    external: true