services:
  app:
    image: your-app:${{ github.sha }} # Použijte stejný tag, jaký byl vytvořen v GitHub Actions
    ports:
      - "50021:50021"
    restart: always
    environment:
      - SERVER_PORT=50021