version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50021:50021"
    restart: always
    environment:
      - SERVER_PORT=50021
    networks:
      - autodl-network
    # Add resource limits
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    # Add healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50021/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Add logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  autodl-network:
    external: true